### ISSUE TITLE
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

### ISSUE THREAD

**Issue by Framington** [lowfuel/progrockdiffusion#143]
Hello lowfuel and community,

I'm reaching out to you guys to hopefully get some help and good suggestions. We've setup progrockdiffusion on two of our three computers in our elementary school already, however the third one is giving me a hard time setting it up and running the initial `python prd.py` command.

Setup: Win 10
Mode: CPU
RAM: 32GB
(installation and usage worked fine on two computers already)
Installation Path: D:\ instead of C:\ (might this be a problem?)

When starting python `prd.py` - it will download the models, and immediately after jump into this error message.

`512x512_diffusion_uncond_finetune_008100 Model downloading. This may take a while...
Traceback (most recent call last):
  File "D:\Miniconda3\envs\progrockdiffusion\lib\urllib\request.py", line 1350, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "D:\Miniconda3\envs\progrockdiffusion\lib\http\client.py", line 1281, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "D:\Miniconda3\envs\progrockdiffusion\lib\http\client.py", line 1327, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "D:\Miniconda3\envs\progrockdiffusion\lib\http\client.py", line 1276, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "D:\Miniconda3\envs\progrockdiffusion\lib\http\client.py", line 1036, in _send_output
    self.send(msg)
  File "D:\Miniconda3\envs\progrockdiffusion\lib\http\client.py", line 976, in send
    self.connect()
  File "D:\Miniconda3\envs\progrockdiffusion\lib\http\client.py", line 948, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "D:\Miniconda3\envs\progrockdiffusion\lib\socket.py", line 728, in create_connection
    raise err
  File "D:\Miniconda3\envs\progrockdiffusion\lib\socket.py", line 716, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "prd.py", line 2300, in <module>
    download_models(diffusion_model, use_secondary_model)
  File "prd.py", line 2256, in download_models
    urllib.request.urlretrieve(diffusion_model.plink, model_file)
  File "D:\Miniconda3\envs\progrockdiffusion\lib\urllib\request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "D:\Miniconda3\envs\progrockdiffusion\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "D:\Miniconda3\envs\progrockdiffusion\lib\urllib\request.py", line 525, in open
    response = self._open(req, data)
  File "D:\Miniconda3\envs\progrockdiffusion\lib\urllib\request.py", line 543, in _open
    '_open', req)
  File "D:\Miniconda3\envs\progrockdiffusion\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "D:\Miniconda3\envs\progrockdiffusion\lib\urllib\request.py", line 1378, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "D:\Miniconda3\envs\progrockdiffusion\lib\urllib\request.py", line 1352, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond>`

Anyone got an idea? From what i've seen in the issues, having it installed somewhere else than C might cause it? Is that true?

Any help is appreciated. :)
Greetings.

**Comment by lowfuel** [comment]
I use the D drive without issues, so I think you're okay there!

Do you know if the machine uses a proxy for web connectivity?

You may be able to get around the issue by copying the "models" sub-directory from one of the working PC's to this one. Then PRD shouldn't need to download anything.  Note: you also need to copy the ".cache\clip" directory from that machine, which is not in progrockdiffusion's directory, it's inside the user home directory. Copy that to the same location on the other PC.

**Comment by Framington** [comment]
Thank you for the timely response, i'll go through your suggestions tomorrow.
