### ISSUE TITLE
GUI : 'progress.png' not such file error 

### ISSUE THREAD

**Issue by Acephalia** [lowfuel/progrockdiffusion#153]
Hello firstly thank you for your work on this.

Unfortunately I'm getting the following errors when attempting to run via the GUI. Tried to search around but came up empty. Any help would be appreciated.

```
Exception in Tkinter callback
Traceback (most recent call last):
  File "\anaconda3\envs\progrockdiffusion\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "prdgui.py", line 144, in run_thread
    show_image()
  File "prdgui.py", line 178, in show_image
    shutil.copyfile('progress.png', 'progress_done.png')
  File "\anaconda3\envs\progrockdiffusion\lib\shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'progress.png'
```

When Saving : 

```
Default settings loaded
Exception in Tkinter callback
Traceback (most recent call last):
  File "\anaconda3\envs\progrockdiffusion\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "prdgui.py", line 110, in save_text
    json_set['symm_loss_scale'] = int(float(x))
ValueError: could not convert string to float: '[2500]*1000'
```
Thank you!

**Comment by lowfuel** [comment]
Hi there!

We're actually going to move prdgui to its own github repo today, so it might be best if you file this issue there.

https://github.com/KnoBuddy/visualdiffusion/

**Comment by KnoBuddy** [comment]
I will look at it in a couple hours. Those are errors I've solved so some
fixes must have been missed making it in.

**Comment by KnoBuddy** [comment]
Quick question, what location are you in when you run the command and what command are you running. If you navigate to /visualdiffusion/ and run ```python prdgui.py``` it won't function correctly. You have to call the GUI from within /progrockdiffusion/ with ```python visualdiffusion\prdgui.py```

**Comment by KnoBuddy** [comment]
This is from an old version of the GUI, the current version has the symmloss scale fixed, and I just submitted a fix for the lack of a progress.png on first run.

Please navigate to the progrockdiffusion folder.

For the first install run:
```git clone https://github.com/KnoBuddy/VisualDiffusion
python visualdiffusion\prdgui.py
```
If you need to update navigate to your progrockdiffusion\visualdiffusion\ folder and run:
```git pull
```

**Comment by Acephalia** [comment]
thank you for your detailed responses and help! I apologise for not realising there was another repo for the GUI. I've reinstalled everything and now running into a new error. I will however post that on the GUI error page.
