### ISSUE TITLE
FeiArt_Handpainted_CG_Diffusion returns error

### ISSUE THREAD

**Issue by WorldTeacher** [lowfuel/progrockdiffusion#160]
I tried testing the different diffusion models, and the FeiArt Model returns an error:
```
Traceback (most recent call last):
  File "prd.py", line 2865, in <module>
    model.load_state_dict(torch.load(f'{model_path}/{diffusion_model.path}', map_location='cpu'))
  File "/home/alexander/anaconda3/envs/progrockdiffusion/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1483, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for UNetModel:
        Unexpected key(s) in state_dict: "label_emb.weight". 
```
I have tried it in the env I normally use, as well as a fresh env, but the error is the same. I am using the latest version of the branch "main"
Here are the settings I am using:
[gui_settings.txt](https://github.com/lowfuel/progrockdiffusion/files/9446030/gui_settings.txt)

**Comment by lowfuel** [comment]
Okay, thanks. I will just remove that one then (someone else added it). I'm not going to troubleshoot other people's models.
