### ISSUE TITLE
Cuda Errors

### ISSUE THREAD

**Issue by BenPharris** [lowfuel/progrockdiffusion#37]
With latest release on Windows 10 Nvidix RTX 2080ti, Intel I'm getting an error on the run. This appears after the progress bar starts for the run. I don't know if this is an issue in my configuration or if this is an error others are running into. Apologies if this is my mistake!

```
 Traceback (most recent call last):
  File "prd.py", line 2872, in <module>
    do_run()
  File "prd.py", line 1559, in do_run
    for j, sample in enumerate(samples):
  File "f:\users\ben\progrock\progrockdiffusion\guided-diffusion\guided_diffusion\gaussian_diffusion.py", line 900, in ddim_sample_loop_progressive
    eta=eta,
  File "f:\users\ben\progrock\progrockdiffusion\guided-diffusion\guided_diffusion\gaussian_diffusion.py", line 674, in ddim_sample
    out = self.condition_score(cond_fn, out_orig, x, t, model_kwargs=model_kwargs)
  File "f:\users\ben\progrock\progrockdiffusion\guided-diffusion\guided_diffusion\respace.py", line 102, in condition_score
    return super().condition_score(self._wrap_model(cond_fn), *args, **kwargs)
  File "f:\users\ben\progrock\progrockdiffusion\guided-diffusion\guided_diffusion\gaussian_diffusion.py", line 400, in condition_score
    x, self._scale_timesteps(t), **model_kwargs
  File "f:\users\ben\progrock\progrockdiffusion\guided-diffusion\guided_diffusion\respace.py", line 128, in __call__
    return self.model(x, new_ts, **kwargs)
  File "prd.py", line 1432, in cond_fn
    t.item()
RuntimeError: CUDA error: misaligned address
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "prd.py", line 2972, in <module>
    torch.cuda.empty_cache()
  File "F:\Users\Ben\anaconda3\envs\progrockdiffusion\lib\site-packages\torch\cuda\memory.py", line 114, in empty_cache
    torch._C._cuda_emptyCache()
RuntimeError: CUDA error: misaligned address
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
```

**Comment by BenPharris** [comment]
The card has 11gb it would appear that that is the case, though the error was slightly odd. Disabling secondary models fixed the issue and led to a successful run. Any suggestions on memory management to be able to use secondary models with this spec?

**Comment by BenPharris** [comment]
Yeah currently running default settings. 

The successful run used only 512x512 and I set 'secondary model' to false. (the output image was just solid purple but I'm assuming that was because of no secondary model)

I think ultimately my spec is just too low to handle new features. It did work with the default models in the previous release.

**Comment by BenPharris** [comment]
There we go. Looks like this was needed to pull it together. Lowered the cut schedule it does work conditionally. I will try to see if I can get vitl14 running. Thanks much!
