### ISSUE TITLE
Some weird cuda thing.

### ISSUE THREAD

**Issue by virtuallyaverage** [lowfuel/progrockdiffusion#39]
I am randomly getting a cuda failure:
  File "prd.py", line 1565, in cond_fn
    timestep = (1000 - t.item()) / 1000
RuntimeError: CUDA error: unspecified launch failure 

It always fails with this as the last line and seems to be connected to how the AI works, since I have got a few runs where I can put 500+ iterations without issue. While other times I can only do ten. To troubleshoot this I set the prompt and all of the randomized settings for the one that ran well to be the inputs on a second run. It ran flawlessly for over an hour.

I have a 2070 super 8gb card, although 8gb is small for AI, I have turned the settings down until it only uses half of the vram (task manager). So I believe lack of available memory is not the main issue. I did run into an issue when installing pytorch where the versions of the pytorch-audio  and pytorch-video where incompatible with the main pytorch dependency that is listed on the instructions page. So I dug around in the versions until I found an older pytorch version that supported them and the newer CUDA version. I don't know if this could be an issue, but I would hate to miss something.

it also seems to work better when I do not have anything open, and have just restarted my computer.

I dont believe it to be a part of the issue, but this happens too(everytime it fails);

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "prd.py", line 3123, in <module>
    torch.cuda.empty_cache()
  File "C:\Users\wes\.conda\envs\progrockdiffusion\lib\site-packages\torch\cuda\memory.py", line 114, in empty_cache
    torch._C._cuda_emptyCache()
RuntimeError: CUDA error: unspecified launch failure

Sorry for the trouble,

**Comment by virtuallyaverage** [comment]
Update:
so I reinstalled cuda through conda and initial testing is promising, since it seems to work with one result I was having issues with before. Testing further currently.

**Comment by virtuallyaverage** [comment]
So after running numerous tests I have yet to run into another error after installing cuda using anaconda, but I also installed microsoft visual studtudio (not code). I don't know what really fixed it, but I would recommend doing both. 

Here is the command I used to install CUDA through conda:
conda install cuda -c nvidia

**Comment by virtuallyaverage** [comment]
the official guide: https://docs.nvidia.com/cuda/pdf/CUDA_Installation_Guide_Windows.pdf
my command can be found on step 2.4.2
