### ISSUE TITLE
Issue running on GCP instance.

### ISSUE THREAD

**Issue by KnoBuddy** [lowfuel/progrockdiffusion#98]
Okay I have tried from complete scratch a few times to get PRD working on a GCP instance. I don't know what I'm doing wrong, and I think maybe my problem is the location of the packages on different versions of linux but I don't have any idea how to resolve them.

Here is the error after complete install and first run:
```
Traceback (most recent call last):
  File "prd.py", line 106, in <module>
    import cv2
  File "/home/kyle/anaconda3/envs/progrockdiffusion/lib/python3.7/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/home/kyle/anaconda3/envs/progrockdiffusion/lib/python3.7/site-packages/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
  File "/home/kyle/anaconda3/envs/progrockdiffusion/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /home/kyle/anaconda3/envs/progrockdiffusion/lib/python3.7/site-packages/cv2/python-3.7/cv2.cpython-37m-x86_64-linux-gnu.so)
```

**Comment by dblunk88** [comment]
> Okay I have tried from complete scratch a few times to get PRD working on a GCP instance. I don't know what I'm doing wrong, and I think maybe my problem is the location of the packages on different versions of linux but I don't have any idea how to resolve them.
> 
> Here is the error after complete install and first run:
> 
> ```
> Traceback (most recent call last):
>   File "prd.py", line 106, in <module>
>     import cv2
>   File "/home/kyle/anaconda3/envs/progrockdiffusion/lib/python3.7/site-packages/cv2/__init__.py", line 181, in <module>
>     bootstrap()
>   File "/home/kyle/anaconda3/envs/progrockdiffusion/lib/python3.7/site-packages/cv2/__init__.py", line 153, in bootstrap
>     native_module = importlib.import_module("cv2")
>   File "/home/kyle/anaconda3/envs/progrockdiffusion/lib/python3.7/importlib/__init__.py", line 127, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
> ImportError: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /home/kyle/anaconda3/envs/progrockdiffusion/lib/python3.7/site-packages/cv2/python-3.7/cv2.cpython-37m-x86_64-linux-gnu.so)
> ```

Try to downgrade to Ubuntu 20.04

**Comment by hrafninn** [comment]
Try this, fixed it for me:
https://stackoverflow.com/a/46613656

**Comment by lowfuel** [comment]
Glad to hear it!
